services:
  - type: web
    name: skythompsonportfolio
    env: python
    region: oregon  # or ohio depending on your preference
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    branch: main
