services:
  - type: web
    name: skythompsonportfolio
    env: python
    plan: free
    region: ohio
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
